### ISSUE TITLE
Interaction manager reference

### ISSUE THREAD

**Issue by vidrzla** [jcorvinus/HandshakeVR#1]
Hi,

i wonder if somehow the interaction manager in ProviderSwitcher.cs got mixed up with the one from Leap.Unity.Interaction;

so the 
UnityEngine.XR.WSA.Input.InteractionManager.instance;

should be 

Leap.Unity.Interaction.InteractionManager.instance;

Best,

Zlatko

**Comment by jcorvinus** [comment]
Yes, the interaction manager should be the one in the leap namespace. Looks like the Unity auto updater broke your copy of the script. Revert all the Handshake scripts to the versions on the repository and don't run the auto-updater on them.

**Comment by vidrzla** [comment]
Off course! I just checked out the latest version and somehow overlooked
the update... thanks!
